export const languages = [
    // Popular - 20 items
    { name: 'Python', icon: 'Py', mode: 'python', category: 'Popular', color: '#3776AB' },
    { name: 'JavaScript', icon: 'JS', mode: 'javascript', category: 'Popular', color: '#F7DF1E' },
    { name: 'Java', icon: '♨', mode: 'text/x-java', category: 'Popular', color: '#007396' },
    { name: 'C', icon: 'C', mode: 'text/x-csrc', category: 'Popular', color: '#A8B9CC' },
    { name: 'C++', icon: 'C++', mode: 'text/x-c++src', category: 'Popular', color: '#00599C' },
    { name: 'HTML', icon: '5', mode: 'xml', category: 'Popular', color: '#E34F26' },
    { name: 'C#', icon: 'C#', mode: 'text/x-csharp', category: 'Popular', color: '#239120' },
    { name: 'PHP', icon: 'PHP', mode: 'text/x-php', category: 'Popular', color: '#777BB4' },
    { name: 'Go', icon: 'Go', mode: 'text/x-go', category: 'Popular', color: '#00ADD8' },
    { name: 'Rust', icon: '🦀', mode: 'text/x-rustsrc', category: 'Popular', color: '#DEA584' },
    { name: 'Kotlin', icon: 'K', mode: 'text/x-kotlin', category: 'Popular', color: '#7F52FF' },
    { name: 'Swift', icon: 'S', mode: 'text/x-swift', category: 'Popular', color: '#F05138' },
    { name: 'Ruby', icon: '♦', mode: 'text/x-ruby', category: 'Popular', color: '#CC342D' },
    { name: 'TypeScript', icon: 'TS', mode: 'text/typescript', category: 'Popular', color: '#3178C6' },
    { name: 'Shell', icon: '$', mode: 'text/x-sh', category: 'Popular', color: '#4EAA25' },
    { name: 'SQL', icon: 'DB', mode: 'text/x-sql', category: 'Popular', color: '#336791' },
    { name: 'R', icon: 'R', mode: 'text/x-rsrc', category: 'Popular', color: '#276DC3' },
    { name: 'Dart', icon: 'D', mode: 'text/x-dart', category: 'Popular', color: '#0175C2' },
    { name: 'Matlab', icon: 'M', mode: 'text/x-octave', category: 'Popular', color: '#E16737' },
    { name: 'Scala', icon: 'Sc', mode: 'text/x-scala', category: 'Popular', color: '#DC322F' },

    // Programming - 20 items
    { name: 'Assembly', icon: 'ASM', mode: 'text/x-gas', category: 'Programming', color: '#6E4C13' },
    { name: 'Lua', icon: 'Lua', mode: 'text/x-lua', category: 'Programming', color: '#000080' },
    { name: 'Fortran', icon: 'F', mode: 'text/x-fortran', category: 'Programming', color: '#4D41B1' },
    { name: 'Cobol', icon: 'C', mode: 'text/x-cobol', category: 'Programming', color: '#003366' },
    { name: 'Pascal', icon: 'P', mode: 'text/x-pascal', category: 'Programming', color: '#E3E3E3' },
    { name: 'Clojure', icon: 'λ', mode: 'text/x-clojure', category: 'Programming', color: '#5881D8' },
    { name: 'Haskell', icon: 'H', mode: 'text/x-haskell', category: 'Programming', color: '#5D4F85' },
    { name: 'Elixir', icon: '💧', mode: 'text/x-elixir', category: 'Programming', color: '#4E275E' },
    { name: 'Erlang', icon: 'E', mode: 'text/x-erlang', category: 'Programming', color: '#A90533' },
    { name: 'F#', icon: 'F', mode: 'text/x-fsharp', category: 'Programming', color: '#B845FC' },
    { name: 'Perl', icon: 'P', mode: 'text/x-perl', category: 'Programming', color: '#39457E' },
    { name: 'Groovy', icon: 'G', mode: 'text/x-groovy', category: 'Programming', color: '#4298B8' },
    { name: 'Julia', icon: 'J', mode: 'text/x-julia', category: 'Programming', color: '#9558B2' },
    { name: 'Lisp', icon: 'L', mode: 'text/x-common-lisp', category: 'Programming', color: '#3FB68B' },
    { name: 'Nim', icon: 'N', mode: 'text/x-nim', category: 'Programming', color: '#FFE900' },
    { name: 'Racket', icon: 'R', mode: 'text/x-racket', category: 'Programming', color: '#3E5BA9' },
    { name: 'Scheme', icon: 'S', mode: 'text/x-scheme', category: 'Programming', color: '#1E4BEC' },
    { name: 'VB.NET', icon: 'VB', mode: 'text/x-vb', category: 'Programming', color: '#0062AD' },
    { name: 'Zig', icon: 'Z', mode: 'text/x-zig', category: 'Programming', color: '#F7A41D' },
    { name: 'OCaml', icon: 'O', mode: 'text/x-ocaml', category: 'Programming', color: '#EC6813' },

    // Web - 20 items
    { name: 'HTML5', icon: '5', mode: 'xml', category: 'Web', color: '#E34F26' },
    { name: 'CSS3', icon: '3', mode: 'css', category: 'Web', color: '#1572B6' },
    { name: 'React', icon: '⚛', mode: 'javascript', category: 'Web', color: '#61DAFB' },
    { name: 'Vue', icon: 'V', mode: 'javascript', category: 'Web', color: '#4FC08D' },
    { name: 'Angular', icon: 'A', mode: 'text/x-typescript', category: 'Web', color: '#DD0031' },
    { name: 'Svelte', icon: 'S', mode: 'javascript', category: 'Web', color: '#FF3E00' },
    { name: 'Tailwind', icon: 'T', mode: 'css', category: 'Web', color: '#38B2AC' },
    { name: 'Bootstrap', icon: 'B', mode: 'css', category: 'Web', color: '#7952B3' },
    { name: 'jQuery', icon: '$', mode: 'javascript', category: 'Web', color: '#0769AD' },
    { name: 'NodeJS', icon: 'N', mode: 'javascript', category: 'Web', color: '#339933' },
    { name: 'Express', icon: 'Ex', mode: 'javascript', category: 'Web', color: '#000000' },
    { name: 'NextJS', icon: 'N', mode: 'javascript', category: 'Web', color: '#000000' },
    { name: 'Vite', icon: 'V', mode: 'javascript', category: 'Web', color: '#646CFF' },
    { name: 'Webpack', icon: 'W', mode: 'javascript', category: 'Web', color: '#8DD6F9' },
    { name: 'Babel', icon: 'B', mode: 'javascript', category: 'Web', color: '#F9DC3E' },
    { name: 'Sass', icon: 'S', mode: 'css', category: 'Web', color: '#CC6699' },
    { name: 'Less', icon: 'L', mode: 'css', category: 'Web', color: '#1D365D' },
    { name: 'PostCSS', icon: 'P', mode: 'css', category: 'Web', color: '#DD3A0A' },
    { name: 'HTMX', icon: 'H', mode: 'xml', category: 'Web', color: '#3366FF' },
    { name: 'AlpineJS', icon: 'A', mode: 'javascript', category: 'Web', color: '#8BC0D0' },

    // Databases - 20 items
    { name: 'MySQL', icon: '🐬', mode: 'text/x-mysql', category: 'Databases', color: '#4479A1' },
    { name: 'PostgreSQL', icon: '🐘', mode: 'text/x-postgres', category: 'Databases', color: '#336791' },
    { name: 'MongoDB', icon: '🍃', mode: 'javascript', category: 'Databases', color: '#47A248' },
    { name: 'Oracle', icon: 'O', mode: 'text/x-plsql', category: 'Databases', color: '#F80000' },
    { name: 'Redis', icon: 'R', mode: 'text/x-redis', category: 'Databases', color: '#DC382D' },
    { name: 'SQLite', icon: '☁', mode: 'text/x-sql', category: 'Databases', color: '#003B57' },
    { name: 'Cassandra', icon: 'C', mode: 'text/x-sql', category: 'Databases', color: '#1287B1' },
    { name: 'MariaDB', icon: 'M', mode: 'text/x-mysql', category: 'Databases', color: '#003545' },
    { name: 'Firebase', icon: 'F', mode: 'javascript', category: 'Databases', color: '#FFCA28' },
    { name: 'DynamoDB', icon: 'D', mode: 'javascript', category: 'Databases', color: '#4053D6' },
    { name: 'CouchDB', icon: 'C', mode: 'javascript', category: 'Databases', color: '#E42528' },
    { name: 'Firestore', icon: 'F', mode: 'javascript', category: 'Databases', color: '#FFCA28' },
    { name: 'Neo4j', icon: 'N', mode: 'text/x-cypher', category: 'Databases', color: '#008CC1' },
    { name: 'Couchbase', icon: 'C', mode: 'javascript', category: 'Databases', color: '#ED1F24' },
    { name: 'InfluxDB', icon: 'I', mode: 'text/x-sql', category: 'Databases', color: '#22ADF6' },
    { name: 'ClickHouse', icon: 'C', mode: 'text/x-sql', category: 'Databases', color: '#FFCC00' },
    { name: 'Fauna', icon: 'F', mode: 'javascript', category: 'Databases', color: '#3A10E5' },
    { name: 'CockroachDB', icon: 'C', mode: 'text/x-sql', category: 'Databases', color: '#6933FF' },
    { name: 'PlanetScale', icon: 'P', mode: 'text/x-mysql', category: 'Databases', color: '#000000' },
    { name: 'Supabase', icon: 'S', mode: 'text/x-postgres', category: 'Databases', color: '#3ECF8E' },
];
